name: Ada (GNAT) On Demand

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild

    - name: Build
      run: gprbuild -j0 -p

    - name: List
      run: ls -lR

    - name: GNAT make
      run: gnatmake hello.adb

    - name: Say Hello
      run: ./hello
